# Generated by Django 4.0 on 2022-06-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_rename_name_author_first_name_author_last_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['last_name'], name='author_auth_last_na_d6297a_idx'),
        ),
    ]
