# Generated by Django 5.0 on 2024-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_blogauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='demo_field',
            field=models.TextField(default='demo'),
        ),
    ]
